---
- set_fact:
    use_become_method: "doas"
  when: ansible_os_family == "OpenBSD"
- set_fact:
    use_become_method: "sudo"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Install gitlab
  become: true
  become_user: "root"
  become_method: "{{ use_become_method }}"
  block:
  - name: Install packages for all Linux hosts
    package:
      name: "{{ pkgs }}"
      state: present
