---
# On vagrant disable support for ipv6
# requires
#   ansible-galaxy collection install ansible.posix
- name: "Disable support for ipv6"
  become: true
  become_user: "root"
  become_method: "{{ use_become_method }}"
  block:
  - ansible.posix.sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1

