---
pkgs:
  - bash-completion
  - apt-file
  - build-essential
  - locales-all
  - mtr
  - python3
  - python3-dev
  - python3-pip
  - python3-venv
  - python3-wheel
  - tmux
  - vim
  - wget
  - zip
# The XKB keyboard model name.
keyboard_model: pc105

# The XKB keyboard layout name.
keyboard_layout: dk

# The XKB keyboard variant components.
keyboard_variant: ''

# The XKB keyboard option components.
keyboard_options: ''

# The behavior of <BackSpace> and <Delete> keys.
keyboard_backspace: guess
