apache_pkgs:
  - bash-completion
  - php7.2-cli
  - php7.2-fpm
  - php7.2-mysql
  - php7.2-json
  - php7.2-opcache
  - php7.2-mbstring
  - php7.2-xml
  - php7.2-gd
  - php7.2-curl
  - libapache2-mod-php
  - php-mysql
  - php-pgsql
  - apache2
  - elinks
