---
- name: "Install GoBGP as a package"
  become: true
  become_user: "root"
  become_method: "{{ use_become_method }}"
  block:
    - name: Install GoBGP
      package:
        name: 
          - gobgpd
          - net-tools
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
