users:
  - name: adue
    comment: Anders Mundt Due
    groups:  root,sudo,adm
    password: '*'
    shell:   "{{ bash_path }}"
    become: yes

  - name: nice
    comment: Nicolai Brunvold Ernst
    groups:  ''
    password: '*'
    shell:   /bin/ksh
    become: yes

  - name: uninth
    comment: Niels Thomas Haugaard
    groups:  root,sudo,adm
    password: '*'
    shell:   "{{ bash_path }}"
    become: yes
