---  
# default become_method sudo shadows for 'doas' so it aparently has to be set explicit
- set_fact:
    cmd: awk -F':' '$2 != "*"  && $2 != "!" { print $1 }' /etc/master.passwd
  when: ansible_os_family == "OpenBSD"
- set_fact:
    cmd: awk -F':' '$2 != "*"  && $2 != "!" && $2 != "!!" { print $1 }' /etc/shadow
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Get list of unmanaged users
  become: true
  become_user: "root"
  become_method: "{{ use_become_method }}"
  block:
  - name: Get list of users with password left
    shell: "{{ cmd }}"
    changed_when: false
    register: users_with_password

  - name: Print list of users with password left
    debug:
      msg: "User: {{ item }}"
    with_items:
      - "{{ users_with_password.stdout_lines }}"

