---
#- name: Set lock
#  include: "../../roles/prevent_simultaneous_deploys/tasks/pre_tasks.yml"

#- set_fact:
#    use_ssl: "{% if env == 'prod' %} 'yes' {% else %} 'no' {% endif %}"
#    is_vagrant: "{% if env == 'prod' %} 'no' {% else %} 'yes' {% endif %}"
#    db_restore: "{% if env == 'prod' %} 'no' {% else %} 'yes' {% endif %}"

- set_fact:
    use_become_method: "doas"
  when: ansible_os_family == "OpenBSD"
- set_fact:
    use_become_method: "sudo"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: print vars
  debug:
    msg: "{{ item }}"
  with_items:
    - "db_restore: {{ restore_db }}"
    - "use_ssl:    {{ use_ssl }}"
    - "development:{{ development }}"

- name: "Install postgresql for DDPS"
  include: "{{ item_task }}"
  with_items:
    - install_packages.yml
    - configure.yml
  loop_control:
    loop_var: item_task
#- name: Release lock
#  include: "../../prevent_simultaneous_deploys/tasks/post_tasks.yml"
